{
 "title": "football",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "team",
    "query": "select team from players_data group by players_data.team"
   },
   {
    "name": "player",
    "query": "select name from players_data where team = '${team:raw}'"
   }
  ]
 },
 "panels": [
  {
   "title": "Player info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Player info",
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT * from players_data where team=[[team]] and name='[[player]]'"
      }
     ]
    }
   ]
  },
  {
   "title": "team Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "defender",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT name,goals,assists,rating from players_data where team in ([[team]]) and position ~ 'defe'"
      }
     ]
    },
    {
     "title": "middlefilder",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT name,goals,assists,rating from players_data where team in ([[team]]) and position ~ 'Mid'"
      }
     ]
    },
    {
     "title": "Attacker",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT name,goals,assists,rating from players_data where team in ([[team]]) and position ~ 'Att'"
      }
     ]
    },
    {
     "title": "stats",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT\n  name,\n  apps,\n  goals,\n  rating\nFROM players_data\nWHERE\n  team IN ([[team]])"
      }
     ]
    }
   ]
  }
 ]
}